### ISSUE TITLE
should we use this names of months?

### ISSUE THREAD

**Issue by ziymed** [hichem2h/flarum-ext-arabic#1]
> جانفي_فيفري_مارس_أفريل_ماي_جوان_جويلية_أوت_سبتمبر_أكتوبر_نوفمبر_ديسمبر

يناير_فبراير_مارس_أبريل_ماي_يونيو_يوليوز_غشت_شتنبر_أكتوبر_نوفمبر_دجنبر

I think from a contry to another they use some specific names شباط الأول ...

[قائمة الشهور السريانية المعربة من اللاتينية والفرنسية](https://ar.wikipedia.org/wiki/شهور_سريانية)

**Comment by yaseralnajjar** [comment]
Yes, it differs from a country to another... but, most people use these:

يناير_فبراير_مارس_أبريل_مايو_يونيو_يوليو_أغسطس_سبتمبر_أكتوبر_نوفمبر_ديسمبر

Since it's just similar to the English pronunciation (at least for me I know these since I was a kid) :smile:
